# Generated by Django 5.2.7 on 2025-11-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_rename_message_usersubmission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
