# Generated by Django 5.2.7 on 2025-11-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_usersubmission_prefix_alter_usersubmission_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load_and_found_submisssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_picture', models.ImageField(blank=True, null=True, upload_to='submission/')),
                ('item_desc', models.TextField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_found', models.CharField(max_length=100)),
                ('item_submitted', models.CharField(max_length=100)),
                ('item_contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
