# Generated by Django 5.2.7 on 2025-11-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_load_and_found_submisssion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Load_and_found_submisssion',
            new_name='Load_and_found_submission',
        ),
    ]
