# Generated by Django 5.2.7 on 2025-11-02 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubmission',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='budget',
            field=models.CharField(choices=[('<500', 'Under $500'), ('500-1000', '$500 - $1,000'), ('1000-1500', '$1,000 - $1,500'), ('1500-2000', '$1,500 - $2,000'), ('2000-2500', '$2,000 - $2,500'), ('>2500', 'Above $2,500')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='submission/'),
        ),
    ]
