# Generated by Django 5.2.7 on 2025-11-05 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_alter_usersubmission_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='prefix',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
